### ISSUE TITLE
Спасибо за работу! 

### ISSUE THREAD

**Issue by SillySabertooth** [bukerok/gh-pages-instruction#2]
Спасибо за создание мануала и еще большее за создание шаблона html

т.е., спасибо за косвенное создание за нас сайта С:
для этого странного информатика

при первой публикации некоторое время он пишет 404 - нет такого сайта
потом его отпустило
видимо, он долго обрабатывал код/долго публиковал
![image](https://user-images.githubusercontent.com/33688874/33206368-ae93841c-d112-11e7-8aef-653941c1fd73.png)

**Comment by bukerok** [comment]
Thank you for the feedback. As far as I understand everything works normal, so I'll close the issue.
